FROM cgr.dev/chainguard/jre

# Kopier quarkus app
COPY --chown=65532 build/quarkus-app /app

EXPOSE 8080
USER 65532

ENTRYPOINT ["java", "-Dquarkus.http.host=0.0.0.0", "-jar", "/app/quarkus-run.jar"]
